version: '3.1'

services:
  server:
    build:
      context: ./php
    container_name: server
    ports:
      - 80:80
    volumes:
      - ./app:/var/www
    links: 
      - database
  database:
    image: "mysql:5.7"
    container_name: 'venda-la-database'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'tiger'
      MYSQL_DATABASE: 'docker'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'tiger'
